<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript">
    jQuery.noConflict();

    function import_metrilo() {
        var metrilo_chunks = <?php echo Mage::helper('core')->jsonEncode($this->getImport()->getChunks()); ?>;
        var total_chunks = <?php echo count($this->getImport()->getChunks()); ?>;
        var chunk_percentage = 100;
        if(total_chunks > 0){
            var chunk_percentage = (100 / total_chunks);
        }
        var sync_chunk = function(chunk_id){
            progress_percents = Math.round(chunk_id * chunk_percentage);
            update_importing_message('Please wait... '+progress_percents+'% done');

            var order_ids = metrilo_chunks[chunk_id];
            // add form_key for magento controller check
            data = {'orders': order_ids, 'form_key': window.FORM_KEY};
            jQuery.post('<?php echo $this->getAjaxUrl(); ?>', data, function(response) {
                new_chunk_id = chunk_id + 1;
                if(metrilo_chunks[new_chunk_id] != undefined){
                    setTimeout(function(){
                        sync_chunk(new_chunk_id);
                    }, 1000);
                }else{
                    update_importing_message("<span style='color: green;'>Done! Please expect up to 30 minutes for your historical data to appear in Metrilo.</span>");
                }

            });

        }

        var update_importing_message = function(message){
            jQuery('#metrilo_import_status').html(message);
        }
        sync_chunk(0);
    }
</script>

<div style="float: left;">
    <h3>Importing your orders and customers</h3>
    <p>
        This tool helps you sync all your orders and customers to Metrilo and can take <strong>up to 20 minutes</strong> to complete. <br />
        It will not affect your website's performance at all since it sends your orders to your Metrilo account in small chunks.  <br /><br />
        Make sure to <strong>not close this page</strong> while importing. Coffee, maybe?
    </p>
</div>
<div style="clear:both"></div>
<?php echo $this->getButtonHtml() ?>
<div style="clear:both"></div>
<div id="metrilo_import_status"></div>
<div style="clear:both"></div>
