<?php $import = $this->getImport(); ?>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript">
    jQuery.noConflict();

    function import_metrilo() {
        var total_chunks = <?php echo $import->getChunks(); ?>;
        var chunk_percentage = 100;
        if(total_chunks > 0){
            var chunk_percentage = (100 / total_chunks);
        }
        // Update button state and text
        jQuery('#metrilo_button').addClass('disabled').attr('disabled', 'disabled').text('Importing orders');

        var errorOccured = false;

        for (var chunk_id = 0; chunk_id < total_chunks; chunk_id ++) {
          progress_percents = Math.round(chunk_id * chunk_percentage);
          update_importing_message('Please wait... '+progress_percents+'% done', true);

          var data = {'chunk_id': chunk_id, 'form_key': window.FORM_KEY};

          jQuery.ajax({
            type: 'POST',
            url: '<?php echo $this->getAjaxUrl(); ?>',
            error: function(response) {
              errorOccured = true;
            },
            data: data,
            async: false
          });

          if (errorOccured === true) {
            break;
          }
        }

        if (errorOccured === false) {
          update_importing_message("<span style='color: green;'>Done! Please expect up to 30 minutes for your historical data to appear in Metrilo.</span>", false);
          jQuery('#metrilo_button').removeClass('disabled').addClass('success').text('Orders imported');
        } else {
          update_importing_message("<span style='color: red;'>There was error while importing your data in Metrilo.</span>", false);
          jQuery('#metrilo_button').removeClass('disabled').removeAttr('disabled').text('Retry import');
        }

        var update_importing_message = function (message, show_loader) {
            if (show_loader)
                message = '<img src="<?php echo $this->getSkinUrl("metrilo/loader.gif"); ?>" />' + message;
            jQuery('#metrilo_import_status').html(message);
        }
    }
</script>

<div style="float: left;">
    <h3>Importing your orders and customers</h3>
    <p>
        This tool helps you sync all your orders and customers to Metrilo and can take <strong>up to 20 minutes</strong> to complete. <br />
        It will not affect your website's performance at all since it sends your orders to your Metrilo account in small chunks.  <br /><br />
        Make sure to <strong>not close this page</strong> while importing. Coffee, maybe?
    </p>
</div>
<div style="clear:both"></div>
<?php echo $this->getButtonHtml() ?>
<div style="clear:both"></div>
<div id="metrilo_import_status"></div>
<div style="clear:both"></div>
