<?php
/** @var Metrilo_Analytics_Block_Adminhtml_System_Config_Form_Hint $this */
?>
<div id="metrilo-info">
    <img src="<?php echo $this->getSkinUrl('metrilo/favicon-metrilo.png') ?>" alt="Metrilo" />
    <div class="text">
        This module was developed by <a href="http://metrilo.com" target="_blank">Metrilo.com</a><br />
        If you encounter any issues, let us know at <a href="mailto:support@metrilo.com">support@metrilo.com</a>. We'll be happy to assist you!<br />
        Plugin version: <?php echo $this->getModuleVersion() ?>
    </div>
</div>
<div style="clear:both;"></div>